# Generated by Django 4.2.16 on 2024-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='navbar_display',
            field=models.BooleanField(default=True),
        ),
    ]
