# Generated by Django 4.2.16 on 2024-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_navbar_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('game', 'Game'), ('console', 'Console'), ('accessory', 'Accessory')], default='console', max_length=50),
        ),
    ]
