# Generated by Django 4.2.16 on 2024-10-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('games', 'Games'), ('consoles', 'Consoles'), ('accessories', 'Accessories')], max_length=20),
        ),
    ]
