# Generated by Django 4.2.16 on 2024-10-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
